### ISSUE TITLE
Confusing 1.month.ago == today

### ISSUE THREAD

**Issue by awronski** [hotchemi/khronos#23]
Why 1.month is 0 based and is not consistent with other properties?

This very confusing when ```1.month.ago == today```

```kotlin
    val monthAgo = 1.month.ago.month
    val today = Dates.today.month
    assert(monthAgo == today)
```

**Comment by DupinC** [comment]
Same issue, I don't understand this line :

https://github.com/hotchemi/khronos/blob/0c4ad729aaa75a60e07501756144aea8650efa48/src/main/kotlin/khronos/IntExtensions.kt#L12
